export const categories = {
  movies: [
    { name: "Inception" },
    { name: "Titanic" },
    { name: "Matrix" },
    { name: "Avatar" },
    { name: "Joker" },
    { name: "Interstellar" },
    { name: "Gladiator" },
    { name: "Avatar 2" },
    { name: "Avengers" },
    { name: "Jurassic Park" },
  ],
  tvshows: [
    { name: "Breaking Bad" },
    { name: "Friends" },
    { name: "Game of Thrones" },
    { name: "Stranger Things" },
    { name: "The Office" },
    { name: "Sherlock" },
    { name: "The Mandalorian" },
    { name: "The Crown" },
    { name: "Black Mirror" },
    { name: "Rick and Morty" },
  ],
  countries: [
    { name: "France" },
    { name: "Brazil" },
    { name: "Japan" },
    { name: "Canada" },
    { name: "Germany" },
    { name: "Australia" },
    { name: "India" },
    { name: "Italy" },
    { name: "Mexico" },
    { name: "Norway" },
  ],
  animals: [
    { name: "Lion" },
    { name: "Tiger" },
    { name: "Elephant" },
    { name: "Giraffe" },
    { name: "Kangaroo" },
    { name: "Penguin" },
    { name: "Dolphin" },
    { name: "Panda" },
    { name: "Zebra" },
    { name: "Cheetah" },
  ],
};
